DROP TABLE IF EXISTS movies CASCADE;

CREATE TABLE movies
(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
title TEXT NOT NULL,
year BIGINT,
director TEXT NOT NULL,
genre TEXT NOT NULL,
thumbs BOOLEAN  
)