DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS actors CASCADE;

CREATE TABLE movies
(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
title TEXT NOT NULL,
year INT,
director TEXT NOT NULL,
genre TEXT NOT NULL,
thumbs BOOLEAN  
);

CREATE TABLE actors
(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
movie_id BIGINT REFERENCES movies(id),
name TEXT NOT NULL,
oscar BOOLEAN 
);